# Generated by Django 4.2.2 on 2023-07-25 17:04

from django.db import migrations
from django.db.migrations import RunPython


def func(apps, schema_editor) -> None:
    from django.core.management import call_command
    call_command("loaddata", 'fixture_data.json')


def reverse_func(apps, schema_editor) -> None:
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [RunPython(func, reverse_func), ]
