# Generated by Django 4.2.2 on 2023-06-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newspaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "published_date",
                    models.DateField(auto_now_add=True, verbose_name="Date Published"),
                ),
                (
                    "topic",
                    models.ManyToManyField(related_name="newspaper", to="agency.topic"),
                ),
            ],
        ),
    ]
